# Form implementation generated from reading ui file 'Model_A.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 763)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_m = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_m.setGeometry(QtCore.QRect(10, 10, 431, 298))
        self.groupBox_m.setObjectName("groupBox_m")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_m)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_m_add = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_add.setObjectName("pushButton_m_add")

        # Connect signal
        self.pushButton_m_add.clicked.connect(self.add_row)

        self.horizontalLayout.addWidget(self.pushButton_m_add)
        self.pushButton_m_del = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_del.setObjectName("pushButton_m_del")
        self.horizontalLayout.addWidget(self.pushButton_m_del)
        self.pushButton_m_sqr = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_sqr.setObjectName("pushButton_m_sqr")
        self.horizontalLayout.addWidget(self.pushButton_m_sqr)
        self.pushButton_m_waste = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_waste.setObjectName("pushButton_m_waste")
        self.horizontalLayout.addWidget(self.pushButton_m_waste)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_m = QtWidgets.QTableWidget(parent=self.groupBox_m)
        self.tableWidget_m.setObjectName("tableWidget_m")
        self.tableWidget_m.setColumnCount(7)
        self.tableWidget_m.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_m.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget_m)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_m_clear = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_clear.setObjectName("pushButton_m_clear")
        self.horizontalLayout_3.addWidget(self.pushButton_m_clear)
        self.pushButton_m_insert = QtWidgets.QPushButton(parent=self.groupBox_m)
        self.pushButton_m_insert.setObjectName("pushButton_m_insert")
        self.horizontalLayout_3.addWidget(self.pushButton_m_insert)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(450, 10, 621, 711))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_print = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_print.setObjectName("pushButton_print")
        self.horizontalLayout_2.addWidget(self.pushButton_print)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget_takeOff = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidget_takeOff.setObjectName("tableWidget_takeOff")
        self.tableWidget_takeOff.setColumnCount(8)
        self.tableWidget_takeOff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_takeOff.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.tableWidget_takeOff)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_row(self):
        current_row = self.tableWidget_m.currentRow()   # Get the current row index

        unit_m = "m"  # Set the unit
        unit_m_cell = QtWidgets.QTableWidgetItem(unit_m)

        # unit = self.tableWidget_m.item(current_row, 4).text()

        new_row = self.tableWidget_m.rowCount()  # Insert one new row at the end of the table
        self.tableWidget_m.insertRow(new_row)

        flags = unit_m_cell.flags()  # Freeze cell
        flags &= ~QtCore.Qt.ItemFlag.ItemIsEditable  # set the cell as read-only
        flags &= ~QtCore.Qt.ItemFlag.ItemIsSelectable  # disable cell selection
        unit_m_cell.setFlags(flags)

        self.tableWidget_m.setItem(0, 4, unit_m_cell)  # set the unit

        # Copy the formatting and logic from the previous row to the new row
        for column in range(self.tableWidget_m.columnCount()):
            item = self.tableWidget_m.item(current_row, column)
            if item is not None:
                new_item = QtWidgets.QTableWidgetItem(item.text())
                flags = item.flags()
                new_item.setFlags(flags)
                self.tableWidget_m.setItem(new_row, column, new_item)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_m.setTitle(_translate("MainWindow", "m"))
        self.pushButton_m_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_m_del.setText(_translate("MainWindow", "Del"))
        self.pushButton_m_sqr.setText(_translate("MainWindow", "Sqr"))
        self.pushButton_m_waste.setText(_translate("MainWindow", "Waste"))
        item = self.tableWidget_m.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "code"))
        self.tableWidget_m.setColumnWidth(0, 40)
        item = self.tableWidget_m.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "times"))
        self.tableWidget_m.setColumnWidth(1, 40)
        item = self.tableWidget_m.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dims"))
        self.tableWidget_m.setColumnWidth(2, 40)
        item = self.tableWidget_m.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "square"))
        self.tableWidget_m.setColumnWidth(3, 50)
        item = self.tableWidget_m.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "unit"))
        self.tableWidget_m.setColumnWidth(4, 30)
        item = self.tableWidget_m.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "description"))
        self.tableWidget_m.setColumnWidth(5, 160)
        item = self.tableWidget_m.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "waste"))
        self.tableWidget_m.setColumnWidth(6, 50)
        self.pushButton_m_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_m_insert.setText(_translate("MainWindow", "Insert"))
        self.groupBox.setTitle(_translate("MainWindow", "Take Off"))
        self.pushButton.setText(_translate("MainWindow", "Abstract"))
        self.pushButton_print.setText(_translate("MainWindow", "Print"))
        item = self.tableWidget_takeOff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "code"))
        self.tableWidget_takeOff.setColumnWidth(0, 40)
        item = self.tableWidget_takeOff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "times"))
        self.tableWidget_takeOff.setColumnWidth(1, 40)
        item = self.tableWidget_takeOff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dims"))
        self.tableWidget_takeOff.setColumnWidth(2, 40)
        item = self.tableWidget_takeOff.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "square"))
        self.tableWidget_takeOff.setColumnWidth(3, 50)
        item = self.tableWidget_takeOff.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "sum"))
        self.tableWidget_takeOff.setColumnWidth(4, 40)
        item = self.tableWidget_takeOff.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "unit"))
        self.tableWidget_takeOff.setColumnWidth(5, 40)
        item = self.tableWidget_takeOff.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "desc"))
        self.tableWidget_takeOff.setColumnWidth(6, 300)
        item = self.tableWidget_takeOff.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "waste"))
        self.tableWidget_takeOff.setColumnWidth(7, 50)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
